train_data_dir: "/Users/iorife/github/crnn-lid/data/youtube/segmented/images/training.csv"
validation_data_dir: "/Users/iorife/github/crnn-lid/data/youtube/segmented/images/validation.csv"
test_data_dir: "/Users/iorife/github/crnn-lid/data/youtube/segmented/images/testing.csv"

batch_size: 128
learning_rate: 0.001
num_epochs: 50

data_loader: "ImageLoader"
color_mode: "L"  # L = bw or RGB
input_shape: [129, 500, 1]

#model: "topcoder_crnn_finetune" # _finetune"
model: "topcoder_crnn"

segment_length: 10  # number of seconds each spectogram represents
pixel_per_second: 50

label_names: ["EN", "DE", "FR", "ES", "CN", "RUS", "PT"]
num_classes: 7




